#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MemoryBox.Resource", IsApplication=true)]

namespace MemoryBox
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cover = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int coverBlank = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int loginButton5 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int loginButton6 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int memBackground = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int memBoxPS = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int monoandroidsplash = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int note = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int round_button = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int SwissAlps = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int text_mem = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int textMem = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int vid_mem = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int vidMem = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int voice_mem = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int voiceMem = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int listView2 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int loginButton = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int loginInput = 2131165188;
			
			// aapt resource value: 0x7f070009
			public const int memFrame = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int memListView = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int textView1 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int textView2 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int titleScreen = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int toMemories = 2131165184;
			
			// aapt resource value: 0x7f070008
			public const int toggleMusic = 2131165192;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Boxes = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Memories = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int avril_14th = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int Mono_Android_Theme_Splash = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int button_text = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
